name: master

on:
  pull_request:
    branches:
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install libpcap-dev
        run: sudo apt-get install -y libpcap-dev

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: -p bugs -p unused

      - name: Build project
        run: |
          make
